---
title: ""
---

> **Research**

#### Publications

* **Ramos, Maria C.**, Lynn Smith-Lovin, and Bethany Young. 2019. *“Intersectional Identities and Stigma Recovery: Affective and Cognitive Responses to Unethical Prosocial Events”* In Identities in Everyday Life, edited by Jan Stets and Richard Serpe. Oxford University Press. 

* **Ramos, Maria C**., and Lynn Smith-Lovin. 2019. *“Social Psychology"*. In Core Concepts in Sociology, edited by J. Michael Ryan. Wiley-Blackwell.

* Cabezas, C. and **M. Ramos**. 2012. *Estudio Exploratorio de Factores Motivacionales Internos y Externos y su Influencia en el Desempeño Docente (Exploratory Study of Intrinsic and Extrinsic Motivational Factors and its Influence on Faculty Performance).* Revista de Investigación en Psicología, 15(1), 47-59. 

#### Works in Progress

* **Ramos, Maria C.** *Values, Master Identities, and the Core of Identity Structures.*

* **Ramos, Maria C.** *Who to Help? Prosocial Behaviors and the Restoration of Tarnished Identities.*

* **Ramos, Maria C.** *Political Belief Structures Across Europe*
