---
title: ""
output:
  html_document:
    theme: paper
    css: 'styles.css'
---

<link rel="stylesheet" href="styles.css" type="text/css">

## Teaching Approach

The courses I lead focus on promoting students' learning in a welcoming environment. I carefully design my courses according to principles of effective learning through in-class activities and a strong writing component. 

### In-class Activities 
Every class session includes in a number of hands-on individual and group activities that aim to develop students' skills in an engaging way. Some activities include: 

* Answering to anonymous online polls to assess comprehension of basic concepts
* Applying knowledge to real case scenarios
* Evaluating claims in journal articles and other media
* Utilizing available tools for a given purpose (e.g., use of library sources for finding relevant literature, using reference managers to produce a reference list)
*Developing original tools for a given purpose (e.g., creating interview guides, survey items)

### Learning Through Writing

The courses I lead invariably incorporate writing.Courses combine short assignments and a bigger project (e.g., a research proposal or research paper). Each of these strategies serves a different purpose in students' learning process. 

#### Short assignments 

Students engage in writing early on and throughout all the course. Because writing can be a daunting task for many students, writing assigments are carefully designed to ease the process and reduce anxiety. For example, some class sessions include short, ungraded, free-writing activities during which students write anything that comes to their mind in response to one or more prompts regarding a course topic (e.g., a reading, short-lecture, or a project they are developing). Distinct prompts aim to achieve different learning goals (e.g. identification, analysis, synthesis, application). In addition, students are instructed not to pay attention to grammar or punctuation during the exercise. Free-writing sessions compel students to engage with the material in a stress-free environment. As a result, students make new connections among concepts and increase the number of observations and questions raised in class. At the end of each session, students write a one-minute paper explaining what they have learned during the session and what questions remain unanswered. 

#### Longer Projects

Longer writing projects provide the opportunity to reflect more deeply on a topic of each student's choice. 
Projects include research proposals, research papers, and essays. Project drafts are turned in early and often. This strategy ensures students do not cram at the end of the term. Instead, students think critically about their project continuously throughout the semester. Students share early drafts with their peers and instructor, and receive feedback so that they can improve their drafts and produce high quality pieces.

## Teaching Experience

#### Methods of Social Research

I have been the instructor of record for this course. 

This course prepares students to evaluate and design research projects to answer social science questions. Step by step, we will walk through how to find and read research articles quickly and efficiently, how to assess existing research, how to formulate your own research questions and hypotheses, and how to design research that answers questions that interest you. Each week, we  discuss short readings about core concepts and methods in social science research. Classes include lecture and a wide variety of hands-on, ungraded individual and group activities to help you apply what you learn to real scenarios. By the end of this course, students will be able to formulate their own research question and produce a short research proposal to answer it.

The primary project for this class is a research proposal, divided into four manageable parts (500-750 words each), so students have the time and feedback they need to create a final proposal (2500 words) that they feel confident in. Assessments will include the final proposal, four drafts of different proposal sections (one draft per section), four short memos (250 words), and in-class participation.

Students of any social science discipline who plan to eventually propose research for their thesis or capstone work will find this course especially helpful, but it is also designed to be accessible to anyone who simply wants to learn a little more about social science research and decide what to think of research findings reported in the media or elsewhere. No Textbook Required.

[Course Syllabus](files/ResearchMethodsSyllabus_final.pdf). 

#### Sociological Inquiry

I have been a discussion section instructor for this course. In this course, students complete a research project over the course of a semester. Discussion sections are geared toward connecting primary theories and empirical findings in sociology with students' own research projects. Discussion sections also help students develop the skills involved in all aspects of the research process: finding reliable sources, critically evaluating arguments, collecting, analyzing, and interpreting data, and effectively communicating findings. Weekly one-hour sessions include a combination of short lectures and discussions about readings followed by hands-on activities through which students can apply the knowledge they acquire at the beginning of the session.  
I complement in-class resources with online tutorials students can access at any time. Sample tutorials include:

* Using NetLogo for aocial simulations
    * [Video tutorial](https://www.youtube.com/watch?v=K1Fp0f4RRZU)
* Using Qualtrics for surveys and survey experiments
    * [Video tutorial](https://youtu.be/2oV3rI3AZTM)

#### Social Network Analysis Workshops

I teach workshops on using R for social network analysis as part of Duke's annual [Social Networks and Health Workshop](https://dnac.ssri.duke.edu/social-networks-health-scholars-training-program-2020.php). R has unique advantages as open source software that allows for implementing sophisticated techniques while keeping  research reproducible. Previous workshops I have taught include:

* Intro to R for Social Network Analysis 
    * [Workshop materials](files/IntrotoR_ExecutedGuide.html)

* Data Cleaning for Social Network Analysis using R.
    * [Workshop materials](files/Data_Cleaning_SNA_ExecuteGuide.html)
    * [Full workshop video](https://www.youtube.com/watch?list=PLwrOoPWTJPLQVpcVNtuXF-c3CZG9TxyXo&time_continue=2&v=P0KXKQmg5So&feature=emb_logo)


#### Other Teching Experience

* Guest Lecturer - Experiments in the Social Sciences

During my time at Duke, I have served as a teaching assistant in a number of courses:

* Social Determinants of U.S. Health Disparities
* Sexuality and Society
* Theory and Society
* Punishment and Society

## Continuous Development

I continue to develop as an instructor supporting active learning and the use of writing methodology to learn.  Certificate in College Teaching program. In addition, Teaching Writing in the Disciplines program. I look forward to applying the knowledge, skills, and tools I have acquired through these experiences in my future teaching activities. 

## Possible courses I can teach

* Social Psychology
* Social Networks
* Self and Society
* Methods of Social Research
* Experimental Design for the Social Sciences
* Quantitative Methods
* Introduction to Sociology
